#version: '3'
#services:
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
##     MONGO_INITDB_ROOT_PASSWORD: test
#      MONGO_INITDB_DATABASE: product-service
#    command: ["--auth", "--port", "27017", "--replSet", "rs0"]
#  init-mongo:
#    image: mongo:latest
#    command: [ "--bind_ip_all", "--port", "27017", "--replSet", "rs0" ]



# Use root/example as user/password credentials
version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "21017:21017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: product-service